# Generated by Django 6.0.4 on 2026-05-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expiry_date', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
