# Generated by Django 6.0.4 on 2026-05-05 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='articles_published_independently',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.article'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='newsletter_published_independently',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.newsletter'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscriptions_to_journalists',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscriptions_to_publishers',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='main_app.publisher'),
        ),
    ]
