# Generated by Django 6.0.4 on 2026-05-07 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_customuser_articles_published_independently_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='articles_published_independently',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='newsletter_published_independently',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscriptions_to_journalists',
            field=models.ManyToManyField(blank=True, related_name='journalist_subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
