# Generated by Django 6.0.4 on 2026-05-13 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_delete_journalist_publisher_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.publisher'),
        ),
    ]
