# Generated by Django 6.0.5 on 2026-05-28 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_newsletter_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='pending_editors',
            field=models.ManyToManyField(blank=True, related_name='editor_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publisher',
            name='pending_journalists',
            field=models.ManyToManyField(blank=True, related_name='journalist_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
